estimator: FasterRCNN
backbone: resnet50
num_classes: 64
task: object_detection
train:
  epochs: 80
  batch_size: 8
  accumulation_steps: 8
  log_frequency: 30
  dataset:
    name: GroceriesReal
    args:
      version: v3
      split: train
val:
  batch_size: 8
  dataset:
    name: GroceriesReal
    args:
      version: v3
      split: val
test:
  batch_size: 8
  dataset:
    name: GroceriesReal
    args:
      version: v3
      split: test
metrics:
  AP:
    name: AveragePrecisionBBox2D
    args:
      iou_threshold: .50
      interpolation: NPointInterpolatedAP
  AR:
    name: AverageRecallBBox2D
    args:
      iou_threshold: .50
      max_detections: 100
optimizer:
  name: Adam
  args:
    lr: 2.0e-4
pretrained: False
pretrained_backbone: True
synchronize_metrics: True
